import '@susu/headless-commerce/styles/globals.scss';

import type { Locale } from '@susu/headless-commerce/config/locale';
import { locales } from '@susu/headless-commerce/config/locale';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const dynamicParams = false;
export const fetchCache = 'only-cache';
export const runtime = 'nodejs';
export const preferredRegion = 'auto';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport = {
  width: 'device-width',
  initiaScale: 1,
};

export async function generateStaticParams() {
  return locales.map(locale => ({ locale }));
}

export type LocaleLayoutProps = {
  children: ReactNode;
  params: {
    locale: Locale;
  };
};

export default function LocaleLayout({ children, params: { locale } }: Readonly<LocaleLayoutProps>) {
  return (
    <html lang={locale}>
      <head>
        <link rel="preconnect" href="https://cdn.suitsupply.com" />
        <link rel="dns-prefetch" href="https://cdn.suitsupply.com" />
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://stm.suitsupply.com" />
        <meta key="robots_image" name="robots" content="max-image-preview:large" />
        <meta key="charset" charSet="utf-8" />
        <link
          rel="preload"
          href="https://cdn.suitsupply.com/fonts/gt-america/gt-america-standard-light.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="https://cdn.suitsupply.com/fonts/gt-america/gt-america-standard-regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="https://cdn.suitsupply.com/fonts/gt-america/gt-america-standard-medium.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="https://cdn.suitsupply.com/image/upload/suitsupply/assets/ss19/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="256x256"
          href="https://cdn.suitsupply.com/image/upload/suitsupply/assets/ss19/favicons/android-chrome-256x256.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="https://cdn.suitsupply.com/image/upload/suitsupply/assets/ss19/favicons/android-chrome-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="https://cdn.suitsupply.com/image/upload/suitsupply/assets/ss19/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://cdn.suitsupply.com/image/upload/suitsupply/assets/ss19/favicons/favicon-16x16.png"
        />
        <meta name="theme-color" content="#fff"></meta>
      </head>
      <body>{children}</body>
    </html>
  );
}
